# -*- coding: utf-8 -*-
"""Curso Machine Learning Alura - Aula #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bAG_I8Tfn_AGp4fZjQG6kardKrT8p7fT
"""

from sklearn.metrics import accuracy_score
from sklearn.svm import LinearSVC
# pelo longo?
# perna curta?
# faz auau?

porco01 = [0, 1, 0]
porco02 = [0, 1, 1]
porco03 = [1, 1, 0]

cachorro01 = [0, 1, 1]
cachorro02 = [1, 0, 1]
cachorro03 = [1, 1, 1]

# porco => 0 , cachorro => 1
treino_x = [porco01, porco02, porco03, cachorro01, cachorro02, cachorro03]

treino_y = [0, 0, 0, 1, 1, 1]

modelo = LinearSVC()

modelo.fit(treino_x, treino_y)

animal_misterioso = [1, 0, 1]

modelo.predict([animal_misterioso])

misterio01 = [1, 1, 1]
misterio02 = [1, 1, 0]
misterio03 = [0, 1, 1]

teste_x = [misterio01, misterio02, misterio03]
teste_y = [1, 0, 0]

previsoes = modelo.predict(teste_x)

previsoes == teste_y


taxa_de_acerto = accuracy_score(teste_y, previsoes)
print("Taxa de acerto de %.2f" % (taxa_de_acerto * 100))
